version: '3'
services:
  strapi:
    image: strapi/strapi
    volumes:
      - ./strapi:/usr/src/strapi
    ports:
      - '1337:1337'
  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - './frontend:/usr/src/frontend'
      - '/frontend/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true    
    

